### PR TITLE
Generalize GenerateProof/VerifyProof

### PR DESCRIPTION
**Pull request by chris-wood**
This will let folks re-use these functions more generically if they so choose.

cc @siyengar, @ananthr

### CODE REVIEW

**Comment by alxdavids** [comment]
It looks like this is re-introducing group elements to the public API, is this a good idea? It doesn't seem to match the rest of the VOPRF API (non-proof-related functions) which operates over bytes.

**Comment by chris-wood** [comment]
> It looks like this is re-introducing group elements to the public API, is this a good idea? It doesn't seem to match the rest of the VOPRF API (non-proof-related functions) which operates over bytes.

Hmm, these are all internal functions, right? Since they're internal, making them operate on elements rather than byte strings seems perfectly fine. (An implementation ought to know how to represent these types.) 

As I see it, the public APIs only include Blind, Evaluate, and Finalize, and those all operate on "public" types like SerializedElements.

**Comment by alxdavids** [comment]
> > It looks like this is re-introducing group elements to the public API, is this a good idea? It doesn't seem to match the rest of the VOPRF API (non-proof-related functions) which operates over bytes.
> 
> Hmm, these are all internal functions, right? Since they're internal, making them operate on elements rather than byte strings seems fine. (An implementation ought to know how to represent and these types locally.)
> 
> As I see it, the public APIs only include Blind, Evaluate, and Finalize, and those all operate on "public" types like SerializedElements that may be received over the wire.

Okay, yeah that makes sense, I was confused. In that case, I think the changes are probably fine. Out of interest, what was the main sticking point with the previous version of the API?

**Review by alxdavids — APPROVED** [review]

**Comment by chris-wood** [comment]
> Okay, yeah that makes sense, I was confused. In that case, I think the changes are probably fine. Out of interest, what was the main sticking point with the previous version of the API?

It wasn't usable by Subodh's draft, which led them to define (yet another) DLEQ proof generation and verification routine. I threw up a [PR based on the changes here](https://github.com/siyengar/voprf-with-metadata/pull/1) that makes these two work really well together.

**Comment by siyengar** [comment]
This looks great. I think the only difference between this and the DLEQ proofs in the other draft at present is that this one uses subtraction for the proofs and the other one uses addition

**Comment by chris-wood** [comment]
> This looks great. I think the only difference between this and the DLEQ proofs in the other draft at present is that this one uses subtraction for the proofs and the other one uses addition

Would you prefer one versus the other? :-)

**Review by siyengar — APPROVED** [review]

**Comment by siyengar** [comment]
> > This looks great. I think the only difference between this and the DLEQ proofs in the other draft at present is that this one uses subtraction for the proofs and the other one uses addition
> 
> Would you prefer one versus the other? :-)

na, don't care

**Review by armfazh — APPROVED** [review]

**Pull request merged**
