### PR TITLE
replaces HTML by ASCII in equation

### PR DESCRIPTION
**Pull request by armfazh**

### CODE REVIEW

**Comment by armfazh** [comment]
looks like the browser disagrees.

https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-voprf#name-rejection-sampling

image

**Comment by chris-wood** [comment]
I fixed this in #374 -- please take a look!

**Comment by armfazh** [comment]
I don't know what is wrong with the changes in this pr, could you please elaborate.
The pro's of these changes is that we don't need to embed HTML codes in the document that is rendered not only in HTML, but PDF and ASCII versions too.

**Comment by chris-wood** [comment]
The problem is that this doesn't render like we'd want it to in HTML. Please take a look at #374 -- this produces the desired output.

**Comment by armfazh** [comment]
declined in favour of PR-374

**Pull request closed without merging**
